### ISSUE TITLE
Category Suggestions Wanted

### ISSUE THREAD

**Issue by chasegiunta** [craftcms/awesome#2]
Categorization is needed for a clean _easy-to-navigate_ list. Unfortunately, it's not always clear where plugins belong. If you have ideas for more categories, or suggestions on where some should be placed, please discuss here or open a PR.

**Comment by bensomething** [comment]
I've been having a think about this, and going over a number of other Awesome collections to see what kind of thing they're doing. I agree that plugins probably don't need to get added here as that seems like it would be quite the undertaking to maintain now that they're coming thick and fast for Craft 3. I think it'd be sufficient to link through to [plugins.craftcms.com](https://plugins.craftcms.com/) for version 3 plugins and [craftplug.in](https://craftplug.in) for version 2.

In regards to categories, I've put together a [dummy page](https://github.com/bensomething/webthings/blob/master/content/content-management/craft.md) in my bensomething/webthings collection to show a potential grouping. Very rough but you get the idea.

- **Documentation**
- **Community**
- **Featured** _(perhaps a silly idea or maybe not)_
- **Plugins** _(but just simple links for Craft 2 and 3, plus any other relevant ones i.e. Plugin Factory)_
- **Resources** _(kind of a catch-all for articles, videos, tools, and so on)_
  - Articles
  - Praises
  - Videos
  - Podcasts
  - Dev Tools
- **Showcase** _(bragging rights)_
  - Official Case Studies
  - Organisations Using Craft
  - Agencies Using Craft

**Comment by chasegiunta** [comment]
@bensomething I dig it. "Featured" may be a bit rough to maintain, and I personally wouldn't want to curate it, but I'm open to the idea if it's feasible for you or others to contribute. Would you care to do a PR on this reorganization?

**Comment by bensomething** [comment]
Hey Chase, I've just pushed through an update to my forked version if you wanted to have a look and see if it's on the right track: https://github.com/bensomething/awesome-craft

Now that there's a solid selection of articles and videos I thought it made sense to start categorising those, but I am completely open to suggestions about what those categories should be.
