### ISSUE TITLE
Removal of Link to indecent content

### ISSUE THREAD

**Issue by stevenjwright** [craftcms/awesome#39]
### Description
I can only assume Johnathan Kelley's website that you link to has been hacked as the site is now completely riddle with pornographic content. 

Just a heads up so this can be removed from the list.

### Steps to reproduce

1. See the 'Awesome Craft CMS List', section 'Getting Started'
Link titled: Getting Started with CraftCMS by Jonathan Kelley - 8 May 2017
The URL is https://www.jonathankelley.design/blog/getting-started-with-craftcms but redirects to https://www.jonathankelley.design/tags/sex_russin
**`NSFW Warning`.**

**Comment by stevenjwright** [comment]
@brandonkelly just fyi!

**Comment by bensomething** [comment]
Than

**Comment by bensomething** [comment]
Thanks for that @stevenjwright, should've picked that one up when I removed another link from that domain. Sorry @brandonkelly!
